feat: add monitorv2 datasource
observeinc/terraform-provider-observe pull request #126
Opened 2024-07-23 18:03 UTC by obs-gh-owengoebel

2024-07-25 20:48 UTC, vikramraman requested changes

2024-07-25 20:48 UTC, vikramraman commented on client/api.go
> +func (c *Client) LookupMonitorV2(ctx context.Context, workspaceId *string, folderId *string, nameExact *string, nameSubstring *string) (*meta.MonitorV2, error) {
Even if the actual api has all these fields, we probably only want to support workspaceId and nameExact in here.

2024-07-25 20:48 UTC, vikramraman commented on observe/data_source_monitor_v2.go
> +			"get_id": { // ObjectId!
We want to be consistent with the naming across data sources, we typically have: `id`, `workspace`, `name` as the fields for looking up stuff, and should go with the same here.

2024-07-25 20:48 UTC, vikramraman commented on observe/data_source_monitor_v2.go
> +			"search_workspace_id": { // ObjectId!
`workspace`

2024-07-25 20:48 UTC, vikramraman commented on observe/data_source_monitor_v2.go
> +			"search_name_exact": {
`name`

2024-07-25 20:48 UTC, vikramraman commented on observe/data_source_monitor_v2.go
> +			"workspace_id": { // ObjectId!
Can be removed, it is redundant with the `workspace` field.

2024-07-25 20:48 UTC, vikramraman commented on observe/data_source_monitor_v2.go
> +			"name": { // String!
same, redundant given `name` above

2024-07-25 20:48 UTC, vikramraman commented on observe/data_source_monitor_v2.go
> +			"id": { // ObjectId!
We want to include an `oid` instead as a computed field.

2024-07-26 20:21 UTC, vikramraman requested changes

2024-07-26 20:21 UTC, vikramraman commented on docs/data-sources/monitor_v2.md
> +- `data_stabilization_delay` (String) expresses the minimum time that should elapse before data is considered "good enough" to evaluate. Choosing a delay really depends on the expectations of latency
This looks odd, it should be computed and not be part of the optional input for this data source

2024-07-26 20:21 UTC, vikramraman commented on docs/data-sources/monitor_v2.md
> +- `lookback_time` (String) optionally describes a duration that must be satisifed by this monitor. It applies to all rules, but is only applicable to rule kinds that utilize it.
Similar comment here, this should not be needed

2024-07-26 22:50 UTC, obs-gh-owengoebel commented on docs/data-sources/monitor_v2.md
> +- `data_stabilization_delay` (String) expresses the minimum time that should elapse before data is considered "good enough" to evaluate. Choosing a delay really depends on the expectations of latency
makes sense. I think I forgot to delete "Optional: true" when adding "Computed: true". Fixed now

2024-07-29 04:14 UTC, vikramraman approved these changes

2024-07-29 04:14 UTC, merged