Monitorv2 action resource
observeinc/terraform-provider-observe pull request #128
Opened 2024-07-24 17:55 UTC by obs-gh-owengoebel

2024-07-29 17:24 UTC, vikramraman requested changes

2024-07-29 17:24 UTC, vikramraman commented on observe/resource_monitor_v2_action.go
> +			"workspace_id": { // ObjectId!
just `workspace`

2024-07-29 17:24 UTC, vikramraman commented on observe/resource_monitor_v2_action.go
> +			"inline": { // Boolean
I believe we only want to support shared actions. So perhaps we should not expose this, and default to false internally.

2024-07-29 17:24 UTC, vikramraman commented on observe/resource_monitor_v2_action.go
> +			"id": { // ObjectId!
`oid` instead of `id`

2024-07-29 17:24 UTC, vikramraman commented on observe/resource_monitor_v2_action.go
> +				Optional: true,
Should the `subject` and `body` be required for an email action? Feels odd that all of these are optional for an email input.

2024-07-29 17:24 UTC, vikramraman commented on observe/resource_monitor_v2_action.go
> +				Optional: true,
Similar question here, should these be required for a webhook input?

2024-07-29 17:24 UTC, vikramraman commented on observe/resource_monitor_v2_action.go
> +				MaxItems: 1,
Should add `ExactlyOneOf: []string{"email", "webhook"}` here and for webhook?

2024-07-29 17:24 UTC, vikramraman commented on observe/resource_monitor_v2_action.go
> +	// TODO
Remove the TODO?

2024-07-29 18:47 UTC, obs-gh-owengoebel commented on observe/resource_monitor_v2_action.go
> +				Optional: true,
They are optional in the schema. Also in general emails don't need to have a subject and a body. I can send an email to myself without specifying either

2024-07-29 18:49 UTC, obs-gh-owengoebel commented on observe/resource_monitor_v2_action.go
> +				Optional: true,
the schema declares these as [MonitorV2WebhookHeader!], which means the user is not required to provide any elements

2024-07-29 22:36 UTC, obs-gh-owengoebel commented on observe/resource_monitor_v2_action.go
> +				Optional: true,
Resolved. The API fills with defaults if not provided.

2024-07-29 22:36 UTC, obs-gh-owengoebel commented on observe/resource_monitor_v2_action.go
> +				Optional: true,
Resolved. The API fills with defaults if not provided.

2024-07-30 20:10 UTC, vikramraman approved these changes

2024-07-30 20:11 UTC, merged