add monv2 destination resource
observeinc/terraform-provider-observe pull request #129
Opened 2024-07-25 18:51 UTC by obs-gh-owengoebel

2024-08-01 22:48 UTC, obs-gh-owengoebel commented on observe/resource_monitor_v2_destination.go
> +					ValidateDiagFunc: validateOID(oid.TypeUser),
yes, it does. I tried setting `users = [data.observe_user.system.oid, "fakeid"]` and `terraform plan` rejected:

```
owen.goebel@ip-172-31-20-192:~/terraform$ terraform plan
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - terraform.observeinc.com/observeinc/observe in /home/owen.goebel/terraform-provider-observe/bin/v0.14.13-19-g8eb1a0fe
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
data.observe_user.system: Reading...
data.observe_workspace.default: Reading...
data.observe_workspace.default: Read complete after 0s [id=41000002]
data.observe_dataset.default: Reading...
data.observe_user.system: Read complete after 0s [id="1001"]
data.observe_dataset.default: Read complete after 0s [id=41000007]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Warning: Insecure API session
│ 
│   with provider["terraform.observeinc.com/observeinc/observe"],
│   on <empty> line 0:
│   (source code not available)
│ 
╵
╷
│ Error: invalid oid
│ 
│   with observe_monitor_v2_action.act,
│   on main.tf line 60, in resource "observe_monitor_v2_action" "act":
│   60:             users = [data.observe_user.system.oid, "fakeid"]
│ 
╵
```

2024-08-02 03:53 UTC, vikramraman requested changes
Just a minor comment

2024-08-02 03:53 UTC, vikramraman commented on observe/resource_monitor_v2_action_test.go
> +								url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
Ah fun :). Hate to do this, but could we go with `https://example.com` similar to the v1 tests?
Don't want our automation hitting youtube :)

2024-08-02 16:22 UTC, obs-gh-owengoebel commented on observe/resource_monitor_v2_action_test.go
> +								url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
done

2024-08-02 17:45 UTC, vikramraman approved these changes

2024-08-02 17:49 UTC, merged