feat: add monitorv2 action datasource
observeinc/terraform-provider-observe pull request #135
Opened 2024-08-05 22:35 UTC by obs-gh-owengoebel

2024-08-05 23:40 UTC, vikramraman requested changes

2024-08-05 23:40 UTC, vikramraman commented on observe/data_source_monitor_v2_action.go
> +				Type:     schema.TypeString,
Should have `ExactlyOneOf` for the name and id fields.

2024-08-05 23:46 UTC, obs-gh-owengoebel commented on observe/data_source_monitor_v2_action.go
> +				Type:     schema.TypeString,
done

2024-08-06 03:54 UTC, vikramraman approved these changes

2024-08-06 03:54 UTC, merged